### ISSUE TITLE
Phial Errors  Missing parameters. Automagic routing needs 3 parameters.

### ISSUE THREAD

**Issue by tablecell** [metalogico/phial#1]
```
$app->route('/test/:name', function() use($app) {

    // render a template with data
    return $app->render('welcome');

});
```
visit http://localhost/test/john 
Phial Errors  Missing parameters. Automagic routing needs 3 parameters.

**Comment by metalogico** [comment]
Hi, you are missing the **$name** variable in your closure declaration.
So Phial, is not recognizing the url routing.
Try changing this:

$app->route('/test/:name', function(**$name**) use($app) {

    // render a template with data
    return $app->render('welcome');

});
